### ISSUE TITLE
fix: SoLoudBackendNotInitedException when soloud.init();

### ISSUE THREAD

**Issue by georgechond94** [alnitak/flutter_soloud#276]
**Description**

Hi, thanks for the great package!

I just updated soloud to the latest version (3.2.4) and I started getting the following error when calling soloud.init();

```
SoLoudBackendNotInitedException (SoLoudBackendNotInitedException: The player is not initialized (on the C++ side).)
```

Any idea why?
Thanks

**Comment by alnitak** [comment]
Hi @georgechond94, can you give some more info? I am more interested in the platform where you are seeing this issue and if it is relevant, some code. Also, the `init` method is the first soloud method you are calling?

To see some more log info, you can try to use the [logging](https://pub.dev/packages/logging) package:

in the pubspec add it: `dart pub add logging`.
Then in your `main.dart`:
```
import 'dart:developer' as dev;
import 'package:logging/logging.dart';
...
void main() async {
  Logger.root.level = kDebugMode ? Level.FINEST : Level.INFO;
  Logger.root.onRecord.listen((record) {
    dev.log(
      record.message,
      time: record.time,
      level: record.level.value,
      name: record.loggerName,
      zone: record.zone,
      error: record.error,
      stackTrace: record.stackTrace,
    );
  });

  WidgetsFlutterBinding.ensureInitialized();

  /// Initialize the player.
  await SoLoud.instance.init();

  ...
```

**Comment by georgechond94** [comment]
Hi @alnitak, thank you for the quick response.

I am using a physical iOS device and init() is the first method I am calling (along with `flutter_recorder`'s init() and `AudioSession`'s configure.)


```
await _soloud.init(channels: Channels.mono, sampleRate: 24000); // this line throws the error.

await _recorder.init(
      sampleRate: 24000,
      channels: recorder.RecorderChannels.mono,
      format: recorder.PCMFormat.s16le,
    );

_session = await AudioSession.instance;
await _session.configure(AudioSessionConfiguration(
      avAudioSessionCategory: AVAudioSessionCategory.playAndRecord,
      avAudioSessionCategoryOptions:
          AVAudioSessionCategoryOptions.allowBluetooth,
      avAudioSessionMode: AVAudioSessionMode.voiceChat,
      avAudioSessionRouteSharingPolicy:
          AVAudioSessionRouteSharingPolicy.defaultPolicy,
      avAudioSessionSetActiveOptions:
          AVAudioSessionSetActiveOptions.notifyOthersOnDeactivation,
      androidAudioAttributes: const AndroidAudioAttributes(
        contentType: AndroidAudioContentType.speech,
        flags: AndroidAudioFlags.none,
        usage: AndroidAudioUsage.voiceCommunication,
      ),
      androidAudioFocusGainType: AndroidAudioFocusGainType.gain,
      androidWillPauseWhenDucked: true,
    ));
```

I set up logging as you suggested, I ll come back with some more info soon

**Comment by alnitak** [comment]
I am not sure, but since I changed the iOS podspec file, maybe you can also try a deeper clean of the pods. I used this script:
```
flutter clean

cd ios
rm -rf Pods
rm -rf Podfile.lock
pod install --repo-update
cd ..

flutter pub get
```

**Comment by georgechond94** [comment]
Interesting, that actually helped, thanks!

**Comment by georgechond94** [comment]
@alnitak hmm, I just tried it with a release build and it happened again. 🫤

**Comment by alnitak** [comment]
So it has been fixed in debug mode but still on release?

**Comment by georgechond94** [comment]
Sorry for the late response - Yeah, exactly. The release build throws the same error

**Comment by FluffyBunniesTasteTheBest** [comment]
Same issue with version 3.3.0 on iOS in production: Crashes at about 1% of my iOS users. 20 Users effected so far.

Any ideas on how to fix or workaround it would be greatly appreciated.

**Comment by FluffyBunniesTasteTheBest** [comment]
@alnitak Thanks for taking a look at this. One thing I've just notice

**Comment by ineffablesam** [comment]
`
flutter: SoLoud init failed ❌ SoLoudBackendNotInitedException: The player is not initialized (on the C++ side).
flutter: #0      SoLoud.init (package:flutter_soloud/src/soloud.dart:297:7)
flutter: <asynchronous suspension>
flutter: #1      main (package:example/main.dart:24:5)
flutter: <asynchronous suspension>
`

Still the same error.
using version   flutter_soloud: 3.3.4

**Comment by revtut** [comment]
We are having the exact same issue on version 3.3.7.
`FlutterError - SoLoudBackendNotInitedException: The player is not initialized (on the C++ side).`

**Comment by leonb2** [comment]
Same here.

**Comment by LatCui** [comment]
same  here

**Comment by LatCui** [comment]
I have identified the reproducibility steps. Every time I open the app, I put it in the background immediately, and then reopen the app. There is a small chance that I can reproduce the problem this way.

**Comment by dyaboykyl** [comment]
We are also seeing this error happen in production. I have added retries to the flutter init in case there was some race condition but it does not seem to help.

**Comment by wantroba** [comment]
I'm facing the same problem. When I close and reopen the app it works, but it's really annoying when it happens

**Comment by sbauly** [comment]
Same issue here!

**Comment by wantroba** [comment]
Has anyone found a workaround for this? I noticed that in my case it happens when I open the app from a silent notification I receive, causing the app to launch in the background.

**Comment by wantroba** [comment]
I managed to create a workaround that worked well for my case. The code is kind of ugly, but it solved the problem:

```
Future<void> init() async {
    if (!_initialized) {
      try {
        await _soLoud.init(sampleRate: 48000, channels: Channels.mono);
      } catch(e){
        await Future.delayed(Duration(seconds: 1));
        return init();
      }
      _initialized = true;
    }
  }
```

Furthermore, I added a line inside the catch block to log the error in Crashlitics, and I'll explain what happens:

My app receives a silent notification and executes some processes. Apparently, on iOS, this causes the app to open and run in the background. While the app is in this background state, I caught an error every second. As soon as I "opened" the app, or rather, brought it to the foreground, the initialization worked, the errors stopped being logged, and the sound worked normally. This might help investigate the problem.

@alnitak I don't have a Mac so I can't debug this problem, but if you want to create a branch with a specific log, just let me know and I can try testing again and retrieve the log via crashlytics.

Update: Apparently, I don't need to open the app and put it in the foreground; after 4 seconds, the init method works. I imagine it's some resource the library is looking for that isn't yet available. But that's just my speculation.

**Comment by alnitak** [comment]
Hi @wantroba, your workaround reminds me of something that could have been fixed in the `dev` branch.

I also started publishing a pre-release on [pub.dev](https://pub.dev/packages/flutter_soloud/versions/4.0.0-pre.2/changelog) if you'd like to try it there.

The pre-release should also fix the audio context on iOS, which may be related to this issue.

I hope that this issue has been fixed, but I need your feedback to close it definitively because I cannot reproduce it.

**Comment by wantroba** [comment]
> Hi [@wantroba](https://github.com/wantroba), your workaround reminds me of something that could have been fixed in the `dev` branch.
> 
> I also started publishing a pre-release on [pub.dev](https://pub.dev/packages/flutter_soloud/versions/4.0.0-pre.2/changelog) if you'd like to try it there.
> 
> The pre-release should also fix the audio context on iOS, which may be related to this issue.
> 
> I hope that this issue has been fixed, but I need your feedback to close it definitively because I cannot reproduce it.

I tried using the pre-release version but couldn't. I'll paste the error log here (I built it via Codemagic because I don't have a Mac):

```
Failed to build iOS app
Error (Xcode): Multiple commands produce '/Users/builder/Library/Developer/Xcode/DerivedData/Runner-edaimyiflreloheqntgnhkmwcclv/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/flutter_soloud.framework/Headers/all.h'

Error (Xcode): Multiple commands produce '/Users/builder/Library/Developer/Xcode/DerivedData/Runner-edaimyiflreloheqntgnhkmwcclv/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/flutter_soloud.framework/Headers/export.h'

Error (Xcode): Multiple commands produce '/Users/builder/Library/Developer/Xcode/DerivedData/Runner-edaimyiflreloheqntgnhkmwcclv/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/flutter_soloud.framework/Headers/fft.h'

Error (Xcode): Multiple commands produce '/Users/builder/Library/Developer/Xcode/DerivedData/Runner-edaimyiflreloheqntgnhkmwcclv/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/flutter_soloud.framework/Headers/linear.h'

Error (Xcode): Multiple commands produce '/Users/builder/Library/Developer/Xcode/DerivedData/Runner-edaimyiflreloheqntgnhkmwcclv/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/flutter_soloud.framework/Headers/metadata.h'

Error (Xcode): Multiple commands produce '/Users/builder/Library/Developer/Xcode/DerivedData/Runner-edaimyiflreloheqntgnhkmwcclv/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/flutter_soloud.framework/Headers/signalsmith-stretch.h'

Error (Xcode): Multiple commands produce '/Users/builder/Library/Developer/Xcode/DerivedData/Runner-edaimyiflreloheqntgnhkmwcclv/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/flutter_soloud.framework/Headers/stft.h'

Error (Xcode): Multiple commands produce '/Users/builder/Library/Developer/Xcode/DerivedData/Runner-edaimyiflreloheqntgnhkmwcclv/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/flutter_soloud.framework/Headers/stream_decoder.h'

Encountered error while archiving for device.


Build failed :|
Failed to build for iOS
```

**Comment by alnitak** [comment]
I think this is happening since I added Swift Package Manager. I've made a little change to the podspec file, and I would be very grateful if you could try using the `dev` branch. I can tell that in release mode it compiles fine locally on iPhone, but I cannot test it on Codemagic.

Just use this in your pubspec.yaml:

```
dependencies:
  flutter_soloud:
    git:
      url: https://github.com/alnitak/flutter_soloud.git
      ref: dev
```

Thanks for helping me and for your time!

**Comment by alnitak** [comment]
This is probably fixed with version 4. Feel free to reopen if the problem persists.
